<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2pPtx1B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2pPtx1B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2pPtx1B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2pPtx1B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2pPtx1B\App_KernelDevDebugContainer([
    'container.build_hash' => '2pPtx1B',
    'container.build_id' => '0c408756',
    'container.build_time' => 1582558438,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2pPtx1B');
